[project]
name = "sysexy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "mido>=1.3.3",
    "python-rtmidi>=1.5.8",
]

[project.scripts]
sysexy = "sysexy.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
